name: Review code

on: [push]
jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - run: composer install
      - name: Install socoladaica/laravel-audit
        run: composer install

      - name: Run larastan
        run: $GITHUB_WORKSPACE/vendor/bin/phpstan analyse -c $GITHUB_WORKSPACE/audit-package.neon
